---
services:
  # https://sing-box.sagernet.org/installation/docker/
  sing-box:
    container_name: sing-box
    image: ghcr.io/sagernet/sing-box
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/sing-box/config.json
    # https://github.com/SagerNet/sing-box/issues/1786
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    network_mode: host
    # ports:
    #   - 19898:19898 # controller
    #   - 17888:17888 # mixed-in
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
